packages:
  - software
  - schema

catalog:
  '@platforma-sdk/tengo-builder': ^2.1.3
  '@platforma-sdk/package-builder': ^2.16.0
  '@platforma-sdk/block-tools': ^2.5.47
  '@platforma-sdk/eslint-config': ^1.0.3

  '@platforma-open/milaboratories.runenv-python-3': ^1.1.14

  'typescript': ~5.5.4
  'turbo': ^2.5.3

  'vite': ^6.3.5
  'rollup-plugin-sourcemaps2': ^0.5.1
  'eslint': ^9.27.0
  'vite-plugin-dts': ^4.5.4

  '@changesets/cli': ^2.29.4
